In [15]:
#import the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
#importing the dataset
dataset = pd.read_csv('D:\Barath Suresh Docs\PROGRAMMING\MACHINE LEARNING\creditcard.csv')
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [17]:
print(x)

[[ 0.00000000e+00 -1.35980713e+00 -7.27811733e-02 ...  1.33558377e-01
  -2.10530535e-02  1.49620000e+02]
 [ 0.00000000e+00  1.19185711e+00  2.66150712e-01 ... -8.98309914e-03
   1.47241692e-02  2.69000000e+00]
 [ 1.00000000e+00 -1.35835406e+00 -1.34016307e+00 ... -5.53527940e-02
  -5.97518406e-02  3.78660000e+02]
 ...
 [ 1.72788000e+05  1.91956501e+00 -3.01253846e-01 ...  4.45477214e-03
  -2.65608286e-02  6.78800000e+01]
 [ 1.72788000e+05 -2.40440050e-01  5.30482513e-01 ...  1.08820735e-01
   1.04532821e-01  1.00000000e+01]
 [ 1.72792000e+05 -5.33412522e-01 -1.89733337e-01 ... -2.41530880e-03
   1.36489143e-02  2.17000000e+02]]


In [18]:
print(y)

[0 0 0 ... 0 0 0]


In [19]:
#splitting the dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 0)

In [20]:
print(x_train)

[[ 5.31500000e+04 -1.11504743e+00  1.03558276e+00 ...  2.29736936e-01
  -7.05913036e-02  1.29500000e+01]
 [ 4.00600000e+04  1.22847256e+00 -1.38826483e-01 ... -6.91781059e-02
   1.89006069e-03  2.55700000e+01]
 [ 1.54865000e+05  1.92614789e+00 -1.98627962e-01 ...  5.27473012e-02
  -3.26215511e-02  6.90000000e+00]
 ...
 [ 7.66160000e+04  1.51260229e+00 -9.49435315e-01 ... -1.41537086e-03
   3.66494418e-03  3.49000000e+01]
 [ 9.72530000e+04  1.79886333e+00 -1.69979073e+00 ... -3.36155803e-02
  -3.24705125e-02  1.71310000e+02]
 [ 7.48870000e+04 -5.89399721e-01  7.47828393e-01 ...  8.65917860e-02
   1.18083774e-01  1.59900000e+01]]


In [21]:
print(x_test)

[[ 1.25821000e+05 -3.23333572e-01  1.05745525e+00 ...  1.08494430e-01
   1.61139167e-01  4.00000000e+01]
 [ 1.57235000e+05 -3.49718405e-01  9.32618570e-01 ...  7.68300272e-02
   1.75561960e-01  1.98000000e+00]
 [ 1.52471000e+05 -1.61471082e+00 -2.40656973e+00 ...  2.86285101e-01
   4.37321868e-01  9.60000000e+01]
 ...
 [ 1.37149000e+05  1.12540206e+00 -2.28899827e+00 ... -2.40867448e-01
  -7.49435187e-03  5.83210000e+02]
 [ 1.60893000e+05  2.06485724e+00  2.85198054e-01 ... -1.03162057e-01
  -6.17434559e-02  2.95000000e+00]
 [ 1.53086000e+05  2.35138178e+00 -1.32522606e+00 ...  7.26919844e-03
  -5.16343390e-02  1.50000000e+01]]


In [22]:
print(y_train)

[0 0 0 ... 0 0 0]


In [23]:
print(y_test)

[0 0 0 ... 0 0 0]


In [24]:
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
ss= StandardScaler()    
x_train= ss.fit_transform(x_train)    
x_test= ss.transform(x_test) 

In [25]:
#training k-nn model
from sklearn.neighbors import KNeighborsClassifier 
classifier= KNeighborsClassifier(n_neighbors = 5) 
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [26]:
#predicting all test results
y_pred = classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [27]:
#making the confusion matrix
from sklearn.metrics import confusion_matrix
cnm = confusion_matrix(y_test, y_pred)
print(cnm)

[[56852     9]
 [   20    81]]


In [28]:
#finding Accuracy score
from sklearn.metrics import accuracy_score
acs = accuracy_score(y_test, y_pred)*100
print("The accuracy score of k-nn model is",acs,"%")

The accuracy score of k-nn model is 99.94908886626172 %


In [29]:
#finding F1 score
from sklearn.metrics import f1_score
fs= f1_score(y_test, y_pred)*100
print("The f1 score of k-nn model is",fs,"%")

The f1 score of k-nn model is 84.81675392670157 %
